const marvelCharacters = [
  {
    ID: 1,
    Name: "Iron Man",
    Real_Name: "Tony Stark",
    Affiliation: "Avengers",
    First_Appearance: 1963,
    Abilities: [
      "Genius Intellect",
      "Powered Armor Suit",
      "Flight",
      "Energy Blasts",
    ],
    Status: "Active",
    ImageSrc: "images/marvel/ironman.png",
  },
  {
    ID: 2,
    Name: "Captain America",
    Real_Name: "Steve Rogers",
    Affiliation: "Avengers",
    First_Appearance: 1941,
    Abilities: [
      "Super Soldier Strength",
      "Enhanced Agility",
      "Indestructible Shield",
    ],
    Status: "Deceased",
    ImageSrc: "images/marvel/captain_america.png",
  },
  {
    ID: 3,
    Name: "Thor",
    Real_Name: "Thor Odinson",
    Affiliation: "Avengers",
    First_Appearance: 1962,
    Abilities: ["Godly Strength", "Mjolnir Control", "Lightning Manipulation"],
    Status: "Active",
    ImageSrc: "images/marvel/thor.png",
  },
  {
    ID: 4,
    Name: "Hulk",
    Real_Name: "Bruce Banner",
    Affiliation: "Avengers",
    First_Appearance: 1962,
    Abilities: [
      "Superhuman Strength",
      "Regeneration",
      "Genius-Level Intellect",
    ],
    Status: "Active",
    ImageSrc: "images/marvel/hulk.png",
  },
  {
    ID: 5,
    Name: "Black Widow",
    Real_Name: "Natasha Romanoff",
    Affiliation: "Avengers",
    First_Appearance: 1964,
    Abilities: ["Martial Arts", "Espionage", "Enhanced Reflexes"],
    Status: "Deceased",
    ImageSrc: "images/marvel/black_widow.png",
  },
  {
    ID: 6,
    Name: "Doctor Strange",
    Real_Name: "Stephen Strange",
    Affiliation: "Sorcerer Supreme",
    First_Appearance: 1963,
    Abilities: ["Mystic Arts", "Time Manipulation", "Astral Projection"],
    Status: "Active",
    ImageSrc: "images/marvel/doctor_strange.png",
  },
  {
    ID: 7,
    Name: "Spider-Man",
    Real_Name: "Peter Parker",
    Affiliation: "Avengers, Spider-Verse",
    First_Appearance: 1962,
    Abilities: ["Wall-Crawling", "Spider-Sense", "Super Agility"],
    Status: "Active",
    ImageSrc: "images/marvel/spider_man.png",
  },
  {
    ID: 8,
    Name: "Black Panther",
    Real_Name: "T’Challa",
    Affiliation: "Avengers, Wakanda",
    First_Appearance: 1966,
    Abilities: [
      "Enhanced Strength",
      "Vibranium Suit",
      "Genius-Level Intellect",
    ],
    Status: "Deceased",
    ImageSrc: "images/marvel/black_panther.png",
  },
  {
    ID: 9,
    Name: "Scarlet Witch",
    Real_Name: "Wanda Maximoff",
    Affiliation: "Avengers",
    First_Appearance: 1964,
    Abilities: ["Chaos Magic", "Reality Warping", "Telekinesis"],
    Status: "Unknown",
    ImageSrc: "images/marvel/scarlet_witch.png",
  },
  {
    ID: 10,
    Name: "Loki",
    Real_Name: "Loki Laufeyson",
    Affiliation: "Asgard, Anti-Hero",
    First_Appearance: 1962,
    Abilities: ["Illusions", "Shapeshifting", "Magic Manipulation"],
    Status: "Active",
    ImageSrc: "images/marvel/loki.png",
  },
  {
    ID: 11,
    Name: "Deadpool",
    Real_Name: "Wade Wilson",
    Affiliation: "X-Men, Anti-Hero",
    First_Appearance: 1991,
    Abilities: ["Regeneration", "Combat Skills", "Fourth Wall Awareness"],
    Status: "Active",
    ImageSrc: "images/marvel/deadpool.png",
  },
  {
    ID: 12,
    Name: "Wolverine",
    Real_Name: "Logan",
    Affiliation: "X-Men",
    First_Appearance: 1974,
    Abilities: ["Healing Factor", "Adamantium Claws", "Enhanced Senses"],
    Status: "Deceased",
    ImageSrc: "images/marvel/wolverine.png",
  },
  {
    ID: 13,
    Name: "Thanos",
    Real_Name: "Thanos",
    Affiliation: "Villain",
    First_Appearance: 1973,
    Abilities: ["Super Strength", "Infinity Gauntlet", "Immortality"],
    Status: "Deceased",
    ImageSrc: "images/marvel/thanos.png",
  },
  {
    ID: 14,
    Name: "Venom",
    Real_Name: "Eddie Brock",
    Affiliation: "Anti-Hero",
    First_Appearance: 1988,
    Abilities: ["Symbiote Suit", "Super Strength", "Shapeshifting"],
    Status: "Active",
    ImageSrc: "images/marvel/venom.png",
  },
  {
    ID: 15,
    Name: "Groot",
    Real_Name: "Groot",
    Affiliation: "Guardians of the Galaxy",
    First_Appearance: 1960,
    Abilities: ["Regeneration", "Super Strength", "Plant Manipulation"],
    Status: "Active",
    ImageSrc: "images/marvel/groot.png",
  },
];
