CREATE DATABASE EmployeeDB;
USE EmployeeDB;

CREATE TABLE Employees (
    P01F01 INT PRIMARY KEY AUTO_INCREMENT,
    P01F02 VARCHAR(255) NOT NULL,
    P01F03 INT NOT NULL,
    P01F04 VARCHAR(10) NOT NULL,
    P01F05 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    P01F06 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

