import {
  onAdaptiveDetailRowPreparing,
  onCellClick,
  onCellDblClick,
  onCellHoverChanged,
  onCellPrepared,
  onContentReady,
  onContextMenuPreparing,
  onDataErrorOccurred,
  onDisposing,
  onEditCanceled,
  onEditCanceling,
  onEditingStart,
  onEditorPrepared,
  onEditorPreparing,
  onExported,
  onExporting,
  onFileSaving,
  onFocusedCellChanged,
  onFocusedCellChanging,
  onFocusedRowChanged,
  onFocusedRowChanging,
  onInitialized,
  onInitNewRow,
  onKeyDown,
  onOptionChanged,
  onRowClick,
  onRowCollapsed,
  onRowCollapsing,
  onRowDblClick,
  onRowExpanded,
  onRowExpanding,
  onRowInserted,
  onRowInserting,
  onRowPrepared,
  onRowRemoved,
  onRowRemoving,
  onRowUpdated,
  onRowUpdating,
  onRowValidating,
  onSaved,
  onSaving,
  onSelectionChanged,
  onToolbarPreparing,
} from "../Event.js";
$(() => {
  $("#gridContainer")
    .dxDataGrid({
      dataSource: marvelCharacters,
      showBorders: true,
      customizeColumns(columns) {
        columns[0].width = 70;
        columns[1].width = 70;
      },
      refreshMode: "full",
      editing: {
        allowAdding: true,
        allowDeleting: true,
        allowUpdating: true,
        confirmDelete: true,
        useIcons: true,
      },
      scrolling: {
        mode: "virtual",
      },
      onEditingStart: onEditingStart,
      onInitNewRow: onInitNewRow,
      onRowInserting: onRowInserting,
      onRowInserted: onRowInserted,
      onRowUpdating: onRowUpdating,
      onRowUpdated: onRowUpdated,
      onRowRemoving: onRowRemoving,
      onRowRemoved: onRowRemoved,
      onSaving: onSaving,
      onSaved: onSaved,
      onEditCanceling: onEditCanceling,
      onEditCanceled: onEditCanceled,
      columns: [
        "Name",
        "Real_Name",
        "Affiliation",
        "First_Appearance",
        "Abilities",
        "Status",
      ],
    })
    .dxDataGrid("instance");
});
