CREATE DATABASE StockDB;
USE StockDB;
DROP DATABASE StockDB;
SELECT * FROM USR01;
SELECT * FROM STK01;
SELECT * FROM PRT01;
SELECT * FROM TRN01;
SELECT * FROM PTS01;

-- Create Users Table
DROP TABLE USR01;
CREATE TABLE USR01 (
    R01F01 INT AUTO_INCREMENT PRIMARY KEY COMMENT 'UserId',
    R01F02 VARCHAR(100) NOT NULL COMMENT 'Username',
    R01F03 VARCHAR(255) NOT NULL UNIQUE COMMENT 'Email',
    R01F04 VARCHAR(255) NOT NULL COMMENT 'PasswordHash',
    R01F05 VARCHAR(255) NOT NULL DEFAULT "User" COMMENT 'Role',
    R01F06 TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'CreatedAt',
    R01F07 TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'UpdatedAt'
);

-- Create Stocks Table
CREATE TABLE STK01 (
    K01F01 INT AUTO_INCREMENT PRIMARY KEY COMMENT 'StockId',
    K01F02 VARCHAR(20) NOT NULL UNIQUE COMMENT 'StockSymbol',
    K01F03 VARCHAR(255) NOT NULL COMMENT 'StockName',
    K01F04 DECIMAL(18, 2) NOT NULL COMMENT 'Price',
    K01F05 DECIMAL(18, 2) COMMENT 'MarketCap',
    K01F06 TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'CreatedAt',
    K01F07 TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'UpdatedAt'
);

-- Portfolio Stocks
CREATE TABLE PTS01 (
    S01F01 INT AUTO_INCREMENT PRIMARY KEY COMMENT 'PortfolioStockId',
    S01F02 INT NOT NULL COMMENT 'UserId',
    S01F03 INT NOT NULL COMMENT 'StockId',
    S01F04 INT NOT NULL DEFAULT 0 COMMENT 'Quantity',
    S01F05 DECIMAL(18, 2) NOT NULL COMMENT 'PurchasePrice',
    S01F06 DECIMAL(18, 2) NOT NULL COMMENT 'CurrentValue',
    S01F07 DECIMAL(18, 2) NOT NULL COMMENT 'TotalValue',
    S01F08 TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'CreatedAt',
    S01F09 TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'UpdatedAt',
    FOREIGN KEY (S01F02) REFERENCES USR01(R01F01),
    FOREIGN KEY (S01F03) REFERENCES STK01(K01F01)
);

-- Create Portfolios Table
CREATE TABLE PRT01 (
    T01F01 INT AUTO_INCREMENT PRIMARY KEY COMMENT 'PortfolioId',
    T01F02 INT COMMENT 'UserId',
    T01F03 VARCHAR(100) NOT NULL COMMENT 'PortfolioName',
    T01F04 DECIMAL(18, 2) DEFAULT 0 COMMENT 'TotalValue',
    T01F05 TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'CreatedAt',
    T01F06 TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'UpdatedAt',
    FOREIGN KEY (T01F02) REFERENCES USR01(R01F01)
);

-- Create Transactions Table
CREATE TABLE TRN01 (
    N01F01 INT AUTO_INCREMENT PRIMARY KEY COMMENT 'TransactionId',
    N01F02 INT COMMENT 'UserId',
    N01F03 INT COMMENT 'StockId',
    N01F04 INT NOT NULL COMMENT 'Quantity',
    N01F05 DECIMAL(18, 2) NOT NULL COMMENT 'PriceAtTransaction',
    N01F06 VARCHAR(20) NOT NULL COMMENT 'TransactionType',
    N01F07 TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'TransactionDate',
    FOREIGN KEY (N01F02) REFERENCES USR01(R01F01),
    FOREIGN KEY (N01F03) REFERENCES STK01(K01F01)
);
