const products = [
  {
    productName: "Generic Cotton Bacon",
    productCategory: "Jenny Terry I",
    productPrice: "753.00",
    productCode: "ZA",
    id: "1",
  },
  {
    productName: "Ergonomic Wooden Keyboard",
    productCategory: "Jenny Terry I",
    productPrice: "523.00",
    productCode: "YZ",
    id: "2",
  },
  {
    productName: "Licensed Granite Hat",
    productCategory: "Jenny Terry I",
    productPrice: "622.00",
    productCode: "XY",
    id: "3",
  },
  {
    productName: "Handcrafted Concrete Shoes",
    productCategory: "Jenny Terry I",
    productPrice: "432.00",
    productCode: "WX",
    id: "4",
  },
  {
    productName: "Incredible Steel Sausages",
    productCategory: "Jenny Terry I",
    productPrice: "876.00",
    productCode: "VU",
    id: "5",
  },
  {
    productName: "Fantastic Rubber Gloves",
    productCategory: "Jenny Terry I",
    productPrice: "345.00",
    productCode: "TS",
    id: "6",
  },
  {
    productName: "Rustic Cotton Keyboard",
    productCategory: "Jenny Terry II",
    productPrice: "234.00",
    productCode: "RQ",
    id: "7",
  },
  {
    productName: "Unbranded Wooden Car",
    productCategory: "Jenny Terry II",
    productPrice: "987.00",
    productCode: "PO",
    id: "8",
  },
  {
    productName: "Tasty Concrete Fish",
    productCategory: "Jenny Terry II",
    productPrice: "123.00",
    productCode: "NM",
    id: "9",
  },
  {
    productName: "Awesome Rubber Chicken",
    productCategory: "Jenny Terry II",
    productPrice: "876.00",
    productCode: "LK",
    id: "10",
  },
  {
    productName: "Small Cotton Table",
    productCategory: "Jenny Terry II",
    productPrice: "564.00",
    productCode: "JI",
    id: "11",
  },
  {
    productName: "Gorgeous Granite Ball",
    productCategory: "Jenny Terry II",
    productPrice: "231.00",
    productCode: "HG",
    id: "12",
  },
  {
    productName: "Elegant Rubber Hat",
    productCategory: "Jenny Terry III",
    productPrice: "652.00",
    productCode: "FE",
    id: "13",
  },
  {
    productName: "Heavy Duty Plastic Tuna",
    productCategory: "Jenny Terry III",
    productPrice: "789.00",
    productCode: "DC",
    id: "14",
  },
  {
    productName: "Lightweight Steel Shirt",
    productCategory: "Jenny Terry III",
    productPrice: "345.00",
    productCode: "BA",
    id: "15",
  },
  {
    productName: "Durable Wooden Pants",
    productCategory: "Jenny Terry III",
    productPrice: "123.00",
    productCode: "ZV",
    id: "16",
  },
  {
    productName: "Soft Concrete Chair",
    productCategory: "Jenny Terry III",
    productPrice: "987.00",
    productCode: "YT",
    id: "17",
  },
  {
    productName: "Warm Granite Bike",
    productCategory: "Jenny Terry III",
    productPrice: "765.00",
    productCode: "XR",
    id: "18",
  },
  {
    productName: "Cool Rubber Gloves",
    productCategory: "Jenny Terry IV",
    productPrice: "543.00",
    productCode: "WP",
    id: "19",
  },
  {
    productName: "Modern Plastic Car",
    productCategory: "Jenny Terry IV",
    productPrice: "321.00",
    productCode: "VO",
    id: "20",
  },
  {
    productName: "Classic Wooden Fish",
    productCategory: "Jenny Terry IV",
    productPrice: "234.00",
    productCode: "TN",
    id: "21",
  },
  {
    productName: "Stylish Cotton Chicken",
    productCategory: "Jenny Terry IV",
    productPrice: "876.00",
    productCode: "SM",
    id: "22",
  },
  {
    productName: "Vintage Granite Table",
    productCategory: "Jenny Terry IV",
    productPrice: "432.00",
    productCode: "PI",
    id: "23",
  },
  {
    productName: "Retro Rubber Ball",
    productCategory: "Jenny Terry IV",
    productPrice: "765.00",
    productCode: "NK",
    id: "24",
  },
  {
    productName: "Eco-friendly Wooden Hat",
    productCategory: "Jenny Terry V",
    productPrice: "876.00",
    productCode: "LH",
    id: "25",
  },
  {
    productName: "Handmade Concrete Tuna",
    productCategory: "Jenny Terry V",
    productPrice: "543.00",
    productCode: "JF",
    id: "26",
  },
  {
    productName: "Artisan Rubber Shirt",
    productCategory: "Jenny Terry V",
    productPrice: "321.00",
    productCode: "HD",
    id: "27",
  },
  {
    productName: "Customized Steel Pants",
    productCategory: "Jenny Terry V",
    productPrice: "234.00",
    productCode: "FB",
    id: "28",
  },
  {
    productName: "Exclusive Cotton Chair",
    productCategory: "Jenny Terry V",
    productPrice: "987.00",
    productCode: "DZ",
    id: "29",
  },
  {
    productName: "Limited Edition Granite Bike",
    productCategory: "Jenny Terry V",
    productPrice: "123.00",
    productCode: "CV",
    id: "30",
  },
  {
    productName: "Genuine Rubber Gloves",
    productCategory: "Jenny Terry VI",
    productPrice: "543.00",
    productCode: "BT",
    id: "31",
  },
  {
    productName: "Original Plastic Car",
    productCategory: "Jenny Terry VI",
    productPrice: "876.00",
    productCode: "AR",
    id: "32",
  },
  {
    productName: "Authentic Wooden Fish",
    productCategory: "Jenny Terry VI",
    productPrice: "654.00",
    productCode: "ZO",
    id: "33",
  },
  {
    productName: "Premium Cotton Chicken",
    productCategory: "Jenny Terry VI",
    productPrice: "321.00",
    productCode: "YN",
    id: "34",
  },
  {
    productName: "Deluxe Granite Table",
    productCategory: "Jenny Terry VI",
    productPrice: "432.00",
    productCode: "XK",
    id: "35",
  },
  {
    productName: "Superior Rubber Ball",
    productCategory: "Jenny Terry VI",
    productPrice: "543.00",
    productCode: "WH",
    id: "36",
  },
  {
    productName: "High-Quality Wooden Hat",
    productCategory: "Jenny Terry VII",
    productPrice: "321.00",
    productCode: "VF",
    id: "37",
  },
  {
    productName: "Top-Grade Concrete Tuna",
    productCategory: "Jenny Terry VII",
    productPrice: "654.00",
    productCode: "DP",
    id: "38",
  },
  {
    productName: "Best-in-Class Rubber Shirt",
    productCategory: "Jenny Terry VII",
    productPrice: "987.00",
    productCode: "BM",
    id: "39",
  },
  {
    productName: "Exceptional Steel Pants",
    productCategory: "Jenny Terry VII",
    productPrice: "876.00",
    productCode: "ZL",
    id: "40",
  },
  {
    productName: "Remarkable Cotton Chair",
    productCategory: "Jenny Terry VII",
    productPrice: "543.00",
    productCode: "YJ",
    id: "41",
  },
  {
    productName: "Noteworthy Granite Bike",
    productCategory: "Jenny Terry VII",
    productPrice: "654.00",
    productCode: "XF",
    id: "42",
  },
  {
    productName: "Impressive Rubber Gloves",
    productCategory: "Jenny Terry VIII",
    productPrice: "321.00",
    productCode: "WQ",
    id: "43",
  },
  {
    productName: "Outstanding Plastic Car",
    productCategory: "Jenny Terry VIII",
    productPrice: "987.00",
    productCode: "VL",
    id: "44",
  },
  {
    productName: "Magnificent Wooden Fish",
    productCategory: "Jenny Terry VIII",
    productPrice: "876.00",
    productCode: "DR",
    id: "45",
  },
  {
    productName: "Splendid Cotton Chicken",
    productCategory: "Jenny Terry VIII",
    productPrice: "543.00",
    productCode: "BP",
    id: "46",
  },
  {
    productName: "Amazing Granite Table",
    productCategory: "Jenny Terry VIII",
    productPrice: "321.00",
    productCode: "ZK",
    id: "47",
  },
  {
    productName: "Stunning Rubber Ball",
    productCategory: "Jenny Terry VIII",
    productPrice: "876.00",
    productCode: "YH",
    id: "48",
  },
  {
    productName: "Incredible Wooden Hat",
    productCategory: "Jenny Terry IX",
    productPrice: "543.00",
    productCode: "XG",
    id: "49",
  },
  {
    productName: "Fantastic Concrete Tuna",
    productCategory: "Jenny Terry IX",
    productPrice: "321.00",
    productCode: "WP",
    id: "50",
  },
];
