const questions = [
  {
    question: "What is the main purpose of an IPO (Initial Public Offering)?",
    options: [
      "To allow a company to raise capital from the public",
      "To let a company take on debt for expansion",
      "To distribute dividends among shareholders",
      "To invest in other companies",
    ],
    correctAnswer: "To allow a company to raise capital from the public",
  },
  {
    question: "Which of the following is considered a 'bull market'?",
    options: [
      "A period when stock prices are generally rising",
      "A period when stock prices are falling",
      "A market with low trading volume",
      "A market dominated by institutional investors",
    ],
    correctAnswer: "A period when stock prices are generally rising",
  },
  {
    question: "What is a stock dividend?",
    options: [
      "A payment made in the form of additional shares",
      "A payment made in cash to shareholders",
      "A penalty for selling stocks early",
      "A bond issued by a company",
    ],
    correctAnswer: "A payment made in the form of additional shares",
  },
  {
    question: "What does 'market capitalization' represent?",
    options: [
      "The total value of a company’s outstanding shares",
      "The number of shares a company has issued",
      "The amount of debt a company holds",
      "The total revenue generated by a company in a year",
    ],
    correctAnswer: "The total value of a company’s outstanding shares",
  },
  {
    question:
      "Which term refers to a stock that is expected to grow faster than the market average?",
    options: [
      "Growth stock",
      "Blue-chip stock",
      "Value stock",
      "Dividend stock",
    ],
    correctAnswer: "Growth stock",
  },
  {
    question: "What is the role of a stockbroker?",
    options: [
      "To facilitate buying and selling of stocks for clients",
      "To regulate the stock exchange",
      "To manage company earnings reports",
      "To set stock prices on the exchange",
    ],
    correctAnswer: "To facilitate buying and selling of stocks for clients",
  },
  {
    question:
      "Which index tracks the performance of 500 large companies in the U.S.?",
    options: [
      "S&P 500",
      "Dow Jones Industrial Average",
      "NASDAQ Composite",
      "FTSE 100",
    ],
    correctAnswer: "S&P 500",
  },
  {
    question: "What is a 'bear market'?",
    options: [
      "A period of declining stock prices",
      "A market with high inflation rates",
      "A market with increasing interest rates",
      "A stable market with no volatility",
    ],
    correctAnswer: "A period of declining stock prices",
  },
  {
    question: "Which of the following represents ownership in a company?",
    options: ["Equity or stock", "Bond", "Option", "Certificate of deposit"],
    correctAnswer: "Equity or stock",
  },
  {
    question: "What does P/E ratio stand for?",
    options: [
      "Price to Earnings ratio",
      "Price to Equity ratio",
      "Profit to Expense ratio",
      "Product to Earnings ratio",
    ],
    correctAnswer: "Price to Earnings ratio",
  },
];

let currentQuestionIndex = 0;

// Display question based on current index
const DisplayQuestion = () => {
  const question = questions[currentQuestionIndex];
  const questionText = document.getElementById("question-text");
  const optionsContainer = document.getElementById("options-container");

  // Update question text
  questionText.innerHTML = `Q${currentQuestionIndex + 1}: ${question.question}`;

  // Clear previous options
  optionsContainer.innerHTML = "";

  // Create options
  question.options.forEach((option, index) => {
    const optionDiv = document.createElement("div");
    optionDiv.classList.add("option");

    const radioInput = document.createElement("input");
    radioInput.type = "radio";
    radioInput.name = "option";
    radioInput.id = `option${index + 1}`;
    radioInput.value = option;

    const label = document.createElement("label");
    label.setAttribute("for", `option${index + 1}`);
    label.textContent = option;

    optionDiv.appendChild(radioInput);
    optionDiv.appendChild(label);
    optionsContainer.appendChild(optionDiv);
  });
};

// Initialize first question
DisplayQuestion();

// Event listeners for navigation buttons
document.getElementById("next-btn").addEventListener("click", () => {
  if (document.querySelector("input[name='option']:checked") === null) {
    alert("Please select an option before proceeding.");
    return; // Stop execution if no option is selected
  }

  if (currentQuestionIndex < questions.length - 1) {
    currentQuestionIndex++;
    DisplayQuestion();
    ProgressBar();
    DisplayTotalQuestions();
  }
});

document.getElementById("prev-btn").addEventListener("click", () => {
  if (currentQuestionIndex > 0) {
    currentQuestionIndex--;
    DisplayQuestion();
    ProgressBar();
    DisplayTotalQuestions();
  }
});

const ProgressBar = () => {
  const progressBar = document.getElementById("progress-bar");
  const progressBarContainer = document.getElementById(
    "progress-bar-container"
  );
  const progress = (currentQuestionIndex / questions.length) * 100;
  progressBar.style.width = `${progress}%`;
  progressBarContainer.setAttribute("aria-valuenow", progress);
  progressBarContainer.setAttribute("aria-valuemin", 0);
  progressBarContainer.setAttribute("aria-valuemax", 100);
};

const DisplayTotalQuestions = () => {
  const TotalQuestions = document.getElementById("total-questions");
  TotalQuestions.innerHTML = `Question ${currentQuestionIndex + 1} of ${
    questions.length
  }`;
  TotalQuestions.setAttribute("class", "text-center");
};
