const marvelCharacters = [
  {
    ID: 1,
    Name: "Iron Man",
    Real_Name: "Tony Stark",
    Affiliation: "Avengers",
    First_Appearance: 1963,
    Abilities: [
      "Genius Intellect",
      "Powered Armor Suit",
      "Flight",
      "Energy Blasts",
    ],
    Status: "Active",
    ImageSrc: "images/marvel/ironman.png",
  },
  {
    ID: 2,
    Name: "Captain America",
    Real_Name: "Steve Rogers",
    Affiliation: "Avengers",
    First_Appearance: 1941,
    Abilities: [
      "Super Soldier Strength",
      "Enhanced Agility",
      "Indestructible Shield",
    ],
    Status: "Deceased",
    ImageSrc: "images/marvel/captain_america.png",
  },
  {
    ID: 3,
    Name: "Thor",
    Real_Name: "Thor Odinson",
    Affiliation: "Avengers",
    First_Appearance: 1962,
    Abilities: ["Godly Strength", "Mjolnir Control", "Lightning Manipulation"],
    Status: "Active",
    ImageSrc: "images/marvel/thor.png",
  },
  {
    ID: 4,
    Name: "Hulk",
    Real_Name: "Bruce Banner",
    Affiliation: "Avengers",
    First_Appearance: 1962,
    Abilities: [
      "Superhuman Strength",
      "Regeneration",
      "Genius-Level Intellect",
    ],
    Status: "Active",
    ImageSrc: "images/marvel/hulk.png",
  },
  {
    ID: 5,
    Name: "Black Widow",
    Real_Name: "Natasha Romanoff",
    Affiliation: "Avengers",
    First_Appearance: 1964,
    Abilities: ["Martial Arts", "Espionage", "Enhanced Reflexes"],
    Status: "Deceased",
    ImageSrc: "images/marvel/black_widow.png",
  },
  {
    ID: 6,
    Name: "Doctor Strange",
    Real_Name: "Stephen Strange",
    Affiliation: "Sorcerer Supreme",
    First_Appearance: 1963,
    Abilities: ["Mystic Arts", "Time Manipulation", "Astral Projection"],
    Status: "Active",
    ImageSrc: "images/marvel/doctor_strange.png",
  },
  {
    ID: 7,
    Name: "Spider-Man",
    Real_Name: "Peter Parker",
    Affiliation: "Avengers, Spider-Verse",
    First_Appearance: 1962,
    Abilities: ["Wall-Crawling", "Spider-Sense", "Super Agility"],
    Status: "Active",
    ImageSrc: "images/marvel/spider_man.png",
  },
  {
    ID: 8,
    Name: "Black Panther",
    Real_Name: "T’Challa",
    Affiliation: "Avengers, Wakanda",
    First_Appearance: 1966,
    Abilities: [
      "Enhanced Strength",
      "Vibranium Suit",
      "Genius-Level Intellect",
    ],
    Status: "Deceased",
    ImageSrc: "images/marvel/black_panther.png",
  },
  {
    ID: 9,
    Name: "Scarlet Witch",
    Real_Name: "Wanda Maximoff",
    Affiliation: "Avengers",
    First_Appearance: 1964,
    Abilities: ["Chaos Magic", "Reality Warping", "Telekinesis"],
    Status: "Unknown",
    ImageSrc: "images/marvel/scarlet_witch.png",
  },
  {
    ID: 10,
    Name: "Loki",
    Real_Name: "Loki Laufeyson",
    Affiliation: "Asgard, Anti-Hero",
    First_Appearance: 1962,
    Abilities: ["Illusions", "Shapeshifting", "Magic Manipulation"],
    Status: "Active",
    ImageSrc: "images/marvel/loki.png",
  },
  {
    ID: 11,
    Name: "Deadpool",
    Real_Name: "Wade Wilson",
    Affiliation: "X-Men, Anti-Hero",
    First_Appearance: 1991,
    Abilities: ["Regeneration", "Combat Skills", "Fourth Wall Awareness"],
    Status: "Active",
    ImageSrc: "images/marvel/deadpool.png",
  },
  {
    ID: 12,
    Name: "Wolverine",
    Real_Name: "Logan",
    Affiliation: "X-Men",
    First_Appearance: 1974,
    Abilities: ["Healing Factor", "Adamantium Claws", "Enhanced Senses"],
    Status: "Deceased",
    ImageSrc: "images/marvel/wolverine.png",
  },
  {
    ID: 13,
    Name: "Thanos",
    Real_Name: "Thanos",
    Affiliation: "Villain",
    First_Appearance: 1973,
    Abilities: ["Super Strength", "Infinity Gauntlet", "Immortality"],
    Status: "Deceased",
    ImageSrc: "images/marvel/thanos.png",
  },
  {
    ID: 14,
    Name: "Venom",
    Real_Name: "Eddie Brock",
    Affiliation: "Anti-Hero",
    First_Appearance: 1988,
    Abilities: ["Symbiote Suit", "Super Strength", "Shapeshifting"],
    Status: "Active",
    ImageSrc: "images/marvel/venom.png",
  },
  {
    ID: 15,
    Name: "Groot",
    Real_Name: "Groot",
    Affiliation: "Guardians of the Galaxy",
    First_Appearance: 1960,
    Abilities: ["Regeneration", "Super Strength", "Plant Manipulation"],
    Status: "Active",
    ImageSrc: "images/marvel/groot.png",
  },
];

const countries = [
  { CountryID: 1, CountryName: "India" },
  { CountryID: 2, CountryName: "USA" },
  { CountryID: 3, CountryName: "Canada" },
  { CountryID: 4, CountryName: "Australia" },
  { CountryID: 5, CountryName: "Germany" },
  { CountryID: 6, CountryName: "France" },
  { CountryID: 7, CountryName: "Japan" },
  { CountryID: 8, CountryName: "China" },
  { CountryID: 9, CountryName: "Brazil" },
  { CountryID: 10, CountryName: "Russia" },
  { CountryID: 11, CountryName: "South Africa" },
  { CountryID: 12, CountryName: "Mexico" },
  { CountryID: 13, CountryName: "Italy" },
  { CountryID: 14, CountryName: "Spain" },
  { CountryID: 15, CountryName: "South Korea" },
  { CountryID: 16, CountryName: "United Kingdom" },
  { CountryID: 17, CountryName: "Argentina" },
  { CountryID: 18, CountryName: "Netherlands" },
  { CountryID: 19, CountryName: "Sweden" },
  { CountryID: 20, CountryName: "Switzerland" },
];

const states = [
  { StateID: 1, StateName: "Gujarat", CountryID: 1 },
  { StateID: 2, StateName: "Maharashtra", CountryID: 1 },
  { StateID: 3, StateName: "Texas", CountryID: 2 },
  { StateID: 4, StateName: "California", CountryID: 2 },
  { StateID: 5, StateName: "Ontario", CountryID: 3 },
  { StateID: 6, StateName: "Quebec", CountryID: 3 },
  { StateID: 7, StateName: "New South Wales", CountryID: 4 },
  { StateID: 8, StateName: "Queensland", CountryID: 4 },
  { StateID: 9, StateName: "Bavaria", CountryID: 5 },
  { StateID: 10, StateName: "Hessen", CountryID: 5 },
  { StateID: 11, StateName: "Île-de-France", CountryID: 6 },
  { StateID: 12, StateName: "Normandy", CountryID: 6 },
  { StateID: 13, StateName: "Tokyo", CountryID: 7 },
  { StateID: 14, StateName: "Osaka", CountryID: 7 },
  { StateID: 15, StateName: "Beijing", CountryID: 8 },
  { StateID: 16, StateName: "Shanghai", CountryID: 8 },
  { StateID: 17, StateName: "São Paulo", CountryID: 9 },
  { StateID: 18, StateName: "Rio de Janeiro", CountryID: 9 },
  { StateID: 19, StateName: "Moscow", CountryID: 10 },
  { StateID: 20, StateName: "Saint Petersburg", CountryID: 10 },
];

const cities = [
  { CityID: 1, CityName: "Rajkot", StateID: 1, CountryID: 1 },
  { CityID: 2, CityName: "Ahmedabad", StateID: 1, CountryID: 1 },
  { CityID: 3, CityName: "Mumbai", StateID: 2, CountryID: 1 },
  { CityID: 4, CityName: "Pune", StateID: 2, CountryID: 1 },
  { CityID: 5, CityName: "Houston", StateID: 3, CountryID: 2 },
  { CityID: 6, CityName: "Dallas", StateID: 3, CountryID: 2 },
  { CityID: 7, CityName: "Los Angeles", StateID: 4, CountryID: 2 },
  { CityID: 8, CityName: "San Francisco", StateID: 4, CountryID: 2 },
  { CityID: 9, CityName: "Toronto", StateID: 5, CountryID: 3 },
  { CityID: 10, CityName: "Ottawa", StateID: 5, CountryID: 3 },
  { CityID: 11, CityName: "Montreal", StateID: 6, CountryID: 3 },
  { CityID: 12, CityName: "Quebec City", StateID: 6, CountryID: 3 },
  { CityID: 13, CityName: "Sydney", StateID: 7, CountryID: 4 },
  { CityID: 14, CityName: "Newcastle", StateID: 7, CountryID: 4 },
  { CityID: 15, CityName: "Brisbane", StateID: 8, CountryID: 4 },
  { CityID: 16, CityName: "Gold Coast", StateID: 8, CountryID: 4 },
  { CityID: 17, CityName: "Munich", StateID: 9, CountryID: 5 },
  { CityID: 18, CityName: "Nuremberg", StateID: 9, CountryID: 5 },
  { CityID: 19, CityName: "Frankfurt", StateID: 10, CountryID: 5 },
  { CityID: 20, CityName: "Darmstadt", StateID: 10, CountryID: 5 },
];
