const marvelCharacters = [
  {
    ID: 1,
    Name: "Iron Man",
    Real_Name: "Tony Stark",
    Affiliation: "Avengers",
    First_Appearance: 1963,
    Abilities: [
      "Genius Intellect",
      "Powered Armor Suit",
      "Flight",
      "Energy Blasts",
    ],
    Status: "<h1>Active</h1>",
    ImageSrc: "images/marvel/ironman.png",
  },
  {
    ID: 2,
    Name: "Captain America",
    Real_Name: "Steve Rogers",
    Affiliation: "Avengers",
    First_Appearance: 1941,
    Abilities: [
      "Super Soldier Strength",
      "Enhanced Agility",
      "Indestructible Shield",
    ],
    Status: "Deceased",
    ImageSrc: "images/marvel/captain_america.png",
  },
  {
    ID: 3,
    Name: "Thor",
    Real_Name: "Thor Odinson",
    Affiliation: "Avengers",
    First_Appearance: 1962,
    Abilities: ["Godly Strength", "Mjolnir Control", "Lightning Manipulation"],
    Status: "Active",
    ImageSrc: "images/marvel/thor.png",
  },
  {
    ID: 4,
    Name: "Hulk",
    Real_Name: "Bruce Banner",
    Affiliation: "Avengers",
    First_Appearance: 1962,
    Abilities: [
      "Superhuman Strength",
      "Regeneration",
      "Genius-Level Intellect",
    ],
    Status: "Active",
    ImageSrc: "images/marvel/hulk.png",
  },
  {
    ID: 5,
    Name: "Black Widow",
    Real_Name: "Natasha Romanoff",
    Affiliation: "Avengers",
    First_Appearance: 1964,
    Abilities: ["Martial Arts", "Espionage", "Enhanced Reflexes"],
    Status: "Deceased",
    ImageSrc: "images/marvel/black_widow.png",
  },
  {
    ID: 6,
    Name: "Doctor Strange",
    Real_Name: "Stephen Strange",
    Affiliation: "Sorcerer Supreme",
    First_Appearance: 1963,
    Abilities: ["Mystic Arts", "Time Manipulation", "Astral Projection"],
    Status: "Active",
    ImageSrc: "images/marvel/doctor_strange.png",
  },
  {
    ID: 7,
    Name: "Spider-Man",
    Real_Name: "Peter Parker",
    Affiliation: "Avengers, Spider-Verse",
    First_Appearance: 1962,
    Abilities: ["Wall-Crawling", "Spider-Sense", "Super Agility"],
    Status: "Active",
    ImageSrc: "images/marvel/spider_man.png",
  },
  {
    ID: 8,
    Name: "Black Panther",
    Real_Name: "T’Challa",
    Affiliation: "Avengers, Wakanda",
    First_Appearance: 1966,
    Abilities: [
      "Enhanced Strength",
      "Vibranium Suit",
      "Genius-Level Intellect",
    ],
    Status: "Deceased",
    ImageSrc: "images/marvel/black_panther.png",
  },
  {
    ID: 9,
    Name: "Scarlet Witch",
    Real_Name: "Wanda Maximoff",
    Affiliation: "Avengers",
    First_Appearance: 1964,
    Abilities: ["Chaos Magic", "Reality Warping", "Telekinesis"],
    Status: "Unknown",
    ImageSrc: "images/marvel/scarlet_witch.png",
  },
  {
    ID: 10,
    Name: "Loki",
    Real_Name: "Loki Laufeyson",
    Affiliation: "Asgard, Anti-Hero",
    First_Appearance: 1962,
    Abilities: ["Illusions", "Shapeshifting", "Magic Manipulation"],
    Status: "Active",
    ImageSrc: "images/marvel/loki.png",
  },
  {
    ID: 11,
    Name: "Deadpool",
    Real_Name: "Wade Wilson",
    Affiliation: "X-Men, Anti-Hero",
    First_Appearance: 1991,
    Abilities: ["Regeneration", "Combat Skills", "Fourth Wall Awareness"],
    Status: "Active",
    ImageSrc: "images/marvel/deadpool.png",
  },
  {
    ID: 12,
    Name: "Wolverine",
    Real_Name: "Logan",
    Affiliation: "X-Men",
    First_Appearance: 1974,
    Abilities: ["Healing Factor", "Adamantium Claws", "Enhanced Senses"],
    Status: "Deceased",
    ImageSrc: "images/marvel/wolverine.png",
  },
  {
    ID: 13,
    Name: "Thanos",
    Real_Name: "Thanos",
    Affiliation: "Villain",
    First_Appearance: 1973,
    Abilities: ["Super Strength", "Infinity Gauntlet", "Immortality"],
    Status: "Deceased",
    ImageSrc: "images/marvel/thanos.png",
  },
  {
    ID: 14,
    Name: "Venom",
    Real_Name: "Eddie Brock",
    Affiliation: "Anti-Hero",
    First_Appearance: 1988,
    Abilities: ["Symbiote Suit", "Super Strength", "Shapeshifting"],
    Status: "Active",
    ImageSrc: "images/marvel/venom.png",
  },
  {
    ID: 15,
    Name: "Groot",
    Real_Name: "Groot",
    Affiliation: "Guardians of the Galaxy",
    First_Appearance: 1960,
    Abilities: ["Regeneration", "Super Strength", "Plant Manipulation"],
    Status: "Active",
    ImageSrc: "images/marvel/groot.png",
  },
];

const countries = [
  { CountryID: 1, CountryName: "India" },
  { CountryID: 2, CountryName: "USA" },
  { CountryID: 3, CountryName: "Canada" },
  { CountryID: 4, CountryName: "Australia" },
  { CountryID: 5, CountryName: "Germany" },
  { CountryID: 6, CountryName: "France" },
  { CountryID: 7, CountryName: "Japan" },
  { CountryID: 8, CountryName: "China" },
  { CountryID: 9, CountryName: "Brazil" },
  { CountryID: 10, CountryName: "Russia" },
  { CountryID: 11, CountryName: "South Africa" },
  { CountryID: 12, CountryName: "Mexico" },
  { CountryID: 13, CountryName: "Italy" },
  { CountryID: 14, CountryName: "Spain" },
  { CountryID: 15, CountryName: "South Korea" },
  { CountryID: 16, CountryName: "United Kingdom" },
  { CountryID: 17, CountryName: "Argentina" },
  { CountryID: 18, CountryName: "Netherlands" },
  { CountryID: 19, CountryName: "Sweden" },
  { CountryID: 20, CountryName: "Switzerland" },
];

const states = [
  { StateID: 1, StateName: "Gujarat", CountryID: 1 },
  { StateID: 2, StateName: "Maharashtra", CountryID: 1 },
  { StateID: 3, StateName: "Texas", CountryID: 2 },
  { StateID: 4, StateName: "California", CountryID: 2 },
  { StateID: 5, StateName: "Ontario", CountryID: 3 },
  { StateID: 6, StateName: "Quebec", CountryID: 3 },
  { StateID: 7, StateName: "New South Wales", CountryID: 4 },
  { StateID: 8, StateName: "Queensland", CountryID: 4 },
  { StateID: 9, StateName: "Bavaria", CountryID: 5 },
  { StateID: 10, StateName: "Hessen", CountryID: 5 },
  { StateID: 11, StateName: "Île-de-France", CountryID: 6 },
  { StateID: 12, StateName: "Normandy", CountryID: 6 },
  { StateID: 13, StateName: "Tokyo", CountryID: 7 },
  { StateID: 14, StateName: "Osaka", CountryID: 7 },
  { StateID: 15, StateName: "Beijing", CountryID: 8 },
  { StateID: 16, StateName: "Shanghai", CountryID: 8 },
  { StateID: 17, StateName: "São Paulo", CountryID: 9 },
  { StateID: 18, StateName: "Rio de Janeiro", CountryID: 9 },
  { StateID: 19, StateName: "Moscow", CountryID: 10 },
  { StateID: 20, StateName: "Saint Petersburg", CountryID: 10 },
];

const cities = [
  { CityID: 1, CityName: "Rajkot", StateID: 1, CountryID: 1 },
  { CityID: 2, CityName: "Ahmedabad", StateID: 1, CountryID: 1 },
  { CityID: 3, CityName: "Mumbai", StateID: 2, CountryID: 1 },
  { CityID: 4, CityName: "Pune", StateID: 2, CountryID: 1 },
  { CityID: 5, CityName: "Houston", StateID: 3, CountryID: 2 },
  { CityID: 6, CityName: "Dallas", StateID: 3, CountryID: 2 },
  { CityID: 7, CityName: "Los Angeles", StateID: 4, CountryID: 2 },
  { CityID: 8, CityName: "San Francisco", StateID: 4, CountryID: 2 },
  { CityID: 9, CityName: "Toronto", StateID: 5, CountryID: 3 },
  { CityID: 10, CityName: "Ottawa", StateID: 5, CountryID: 3 },
  { CityID: 11, CityName: "Montreal", StateID: 6, CountryID: 3 },
  { CityID: 12, CityName: "Quebec City", StateID: 6, CountryID: 3 },
  { CityID: 13, CityName: "Sydney", StateID: 7, CountryID: 4 },
  { CityID: 14, CityName: "Newcastle", StateID: 7, CountryID: 4 },
  { CityID: 15, CityName: "Brisbane", StateID: 8, CountryID: 4 },
  { CityID: 16, CityName: "Gold Coast", StateID: 8, CountryID: 4 },
  { CityID: 17, CityName: "Munich", StateID: 9, CountryID: 5 },
  { CityID: 18, CityName: "Nuremberg", StateID: 9, CountryID: 5 },
  { CityID: 19, CityName: "Frankfurt", StateID: 10, CountryID: 5 },
  { CityID: 20, CityName: "Darmstadt", StateID: 10, CountryID: 5 },
];

const users = [
  {
    userID: 1,
    userName: "Amit Sharma",
    CountryName: "India",
    StateName: "Maharashtra",
    CityName: "Mumbai",
  },
  {
    userID: 2,
    userName: "Priya Singh",
    CountryName: "India",
    StateName: "Maharashtra",
    CityName: "Pune",
  },
  {
    userID: 3,
    userName: "Rajesh Kumar",
    CountryName: "India",
    StateName: "Delhi",
    CityName: "New Delhi",
  },
  {
    userID: 4,
    userName: "Anita Desai",
    CountryName: "India",
    StateName: "Delhi",
    CityName: "New Delhi",
  },
  {
    userID: 5,
    userName: "Suresh Patel",
    CountryName: "India",
    StateName: "Gujarat",
    CityName: "Ahmedabad",
  },
  {
    userID: 6,
    userName: "Neha Mehta",
    CountryName: "India",
    StateName: "Gujarat",
    CityName: "Surat",
  },
  {
    userID: 7,
    userName: "Vikram Joshi",
    CountryName: "India",
    StateName: "Karnataka",
    CityName: "Bangalore",
  },
  {
    userID: 8,
    userName: "Pooja Agarwal",
    CountryName: "India",
    StateName: "Karnataka",
    CityName: "Bangalore",
  },
  {
    userID: 9,
    userName: "Rahul Verma",
    CountryName: "India",
    StateName: "Tamil Nadu",
    CityName: "Chennai",
  },
  {
    userID: 10,
    userName: "Sunita Reddy",
    CountryName: "India",
    StateName: "Tamil Nadu",
    CityName: "Chennai",
  },
  {
    userID: 11,
    userName: "Anil Kapoor",
    CountryName: "India",
    StateName: "Rajasthan",
    CityName: "Jaipur",
  },
  {
    userID: 12,
    userName: "Meena Jain",
    CountryName: "India",
    StateName: "Rajasthan",
    CityName: "Udaipur",
  },
  {
    userID: 13,
    userName: "Kiran Deshmukh",
    CountryName: "India",
    StateName: "Maharashtra",
    CityName: "Nagpur",
  },
  {
    userID: 14,
    userName: "Manoj Nair",
    CountryName: "India",
    StateName: "Kerala",
    CityName: "Kochi",
  },
  {
    userID: 15,
    userName: "Sonal Gupta",
    CountryName: "India",
    StateName: "Uttar Pradesh",
    CityName: "Lucknow",
  },
  {
    userID: 16,
    userName: "Ravi Yadav",
    CountryName: "India",
    StateName: "Uttar Pradesh",
    CityName: "Kanpur",
  },
  {
    userID: 17,
    userName: "Alok Mishra",
    CountryName: "India",
    StateName: "Madhya Pradesh",
    CityName: "Bhopal",
  },
  {
    userID: 18,
    userName: "Smita Kulkarni",
    CountryName: "India",
    StateName: "Maharashtra",
    CityName: "Mumbai",
  },
  {
    userID: 19,
    userName: "Deepak Gupta",
    CountryName: "India",
    StateName: "Haryana",
    CityName: "Gurgaon",
  },
  {
    userID: 20,
    userName: "Anjali Chopra",
    CountryName: "India",
    StateName: "Punjab",
    CityName: "Chandigarh",
  },
  {
    userID: 21,
    userName: "Nitin Singh",
    CountryName: "India",
    StateName: "Punjab",
    CityName: "Amritsar",
  },
  {
    userID: 22,
    userName: "Bhavna Sharma",
    CountryName: "India",
    StateName: "Haryana",
    CityName: "Faridabad",
  },
  {
    userID: 23,
    userName: "Rohit Khanna",
    CountryName: "India",
    StateName: "West Bengal",
    CityName: "Kolkata",
  },
  {
    userID: 24,
    userName: "Sneha Bose",
    CountryName: "India",
    StateName: "West Bengal",
    CityName: "Kolkata",
  },
  {
    userID: 25,
    userName: "Arjun Rai",
    CountryName: "India",
    StateName: "Bihar",
    CityName: "Patna",
  },
  {
    userID: 26,
    userName: "Kavita Sinha",
    CountryName: "India",
    StateName: "Bihar",
    CityName: "Patna",
  },
  {
    userID: 27,
    userName: "Sanjay Thakur",
    CountryName: "India",
    StateName: "Himachal Pradesh",
    CityName: "Shimla",
  },
  {
    userID: 28,
    userName: "Divya Rajput",
    CountryName: "India",
    StateName: "Himachal Pradesh",
    CityName: "Manali",
  },
  {
    userID: 29,
    userName: "Vijay Singh",
    CountryName: "India",
    StateName: "Uttarakhand",
    CityName: "Dehradun",
  },
  {
    userID: 30,
    userName: "Swati Rawat",
    CountryName: "India",
    StateName: "Uttarakhand",
    CityName: "Haridwar",
  },
  {
    userID: 31,
    userName: "Kunal Malhotra",
    CountryName: "India",
    StateName: "Chhattisgarh",
    CityName: "Raipur",
  },
  {
    userID: 32,
    userName: "Pallavi Sahu",
    CountryName: "India",
    StateName: "Chhattisgarh",
    CityName: "Bilaspur",
  },
  {
    userID: 33,
    userName: "Gaurav Saxena",
    CountryName: "India",
    StateName: "Jharkhand",
    CityName: "Ranchi",
  },
  {
    userID: 34,
    userName: "Anushka Sinha",
    CountryName: "India",
    StateName: "Jharkhand",
    CityName: "Jamshedpur",
  },
  {
    userID: 35,
    userName: "Mahesh Reddy",
    CountryName: "India",
    StateName: "Telangana",
    CityName: "Hyderabad",
  },
  {
    userID: 36,
    userName: "Shweta Iyer",
    CountryName: "India",
    StateName: "Telangana",
    CityName: "Hyderabad",
  },
  {
    userID: 37,
    userName: "Prakash Naik",
    CountryName: "India",
    StateName: "Goa",
    CityName: "Panaji",
  },
  {
    userID: 38,
    userName: "Lata Fernandes",
    CountryName: "India",
    StateName: "Goa",
    CityName: "Margao",
  },
  {
    userID: 39,
    userName: "Aakash Mehta",
    CountryName: "India",
    StateName: "Maharashtra",
    CityName: "Mumbai",
  },
  {
    userID: 40,
    userName: "Ritika Desai",
    CountryName: "India",
    StateName: "Maharashtra",
    CityName: "Pune",
  },
  {
    userID: 41,
    userName: "Siddharth Chaturvedi",
    CountryName: "India",
    StateName: "Delhi",
    CityName: "New Delhi",
  },
  {
    userID: 42,
    userName: "Rashmi Kapoor",
    CountryName: "India",
    StateName: "Delhi",
    CityName: "New Delhi",
  },
  {
    userID: 43,
    userName: "Varun Agarwal",
    CountryName: "India",
    StateName: "Uttar Pradesh",
    CityName: "Noida",
  },
  {
    userID: 44,
    userName: "Nisha Gupta",
    CountryName: "India",
    StateName: "Uttar Pradesh",
    CityName: "Ghaziabad",
  },
  {
    userID: 45,
    userName: "Tarun Bhatia",
    CountryName: "India",
    StateName: "Punjab",
    CityName: "Ludhiana",
  },
  {
    userID: 46,
    userName: "Pallavi Kaur",
    CountryName: "India",
    StateName: "Punjab",
    CityName: "Jalandhar",
  },
  {
    userID: 47,
    userName: "Ramesh Rao",
    CountryName: "India",
    StateName: "Andhra Pradesh",
    CityName: "Vijayawada",
  },
  {
    userID: 48,
    userName: "Usha Nair",
    CountryName: "India",
    StateName: "Kerala",
    CityName: "Trivandrum",
  },
  {
    userID: 49,
    userName: "Ajay Kumar",
    CountryName: "India",
    StateName: "Bihar",
    CityName: "Patna",
  },
  {
    userID: 50,
    userName: "Kriti Verma",
    CountryName: "India",
    StateName: "Rajasthan",
    CityName: "Jaipur",
  },
];

const orderData = [
  {
    orderId: "ORD001",
    customer: "Alice Johnson",
    orderStatus: "Shipped",
    totalAmount: 150.75,
    discount: 10,
    deliveryDate: "2025-02-15",
  },
  {
    orderId: "ORD002",
    customer: "Bob Smith",
    orderStatus: "Pending",
    totalAmount: 89.99,
    discount: 0,
    deliveryDate: "2025-02-25",
  },
  {
    orderId: "ORD003",
    customer: "John Doe",
    orderStatus: "Cancelled",
    totalAmount: 200.5,
    discount: 5,
    deliveryDate: "2025-02-10",
  },
  {
    orderId: "ORD004",
    customer: "Eve Adams",
    orderStatus: "Delivered",
    totalAmount: 45.0,
    discount: 0,
    deliveryDate: "2025-02-20",
  },
  {
    orderId: "ORD005",
    customer: "Charlie Brown",
    orderStatus: "Shipped",
    totalAmount: 120.0,
    discount: 15,
    deliveryDate: "2025-02-18",
  },
  {
    orderId: "ORD006",
    customer: "David Wilson",
    orderStatus: "Pending",
    totalAmount: 75.25,
    discount: 0,
    deliveryDate: "2025-02-22",
  },
  {
    orderId: "ORD007",
    customer: "Fiona White",
    orderStatus: "Cancelled",
    totalAmount: 300.0,
    discount: 20,
    deliveryDate: "2025-02-12",
  },
  {
    orderId: "ORD008",
    customer: "George Harris",
    orderStatus: "Delivered",
    totalAmount: 50.0,
    discount: 0,
    deliveryDate: "2025-02-24",
  },
  {
    orderId: "ORD009",
    customer: "Helen Clark",
    orderStatus: "Shipped",
    totalAmount: 99.99,
    discount: 5,
    deliveryDate: "2025-02-16",
  },
  {
    orderId: "ORD010",
    customer: "Ivy King",
    orderStatus: "Pending",
    totalAmount: 85.5,
    discount: 0,
    deliveryDate: "2025-02-27",
  },
  {
    orderId: "ORD011",
    customer: "Jack Turner",
    orderStatus: "Cancelled",
    totalAmount: 150.0,
    discount: 10,
    deliveryDate: "2025-02-14",
  },
  {
    orderId: "ORD012",
    customer: "Karen Lewis",
    orderStatus: "Delivered",
    totalAmount: 65.0,
    discount: 0,
    deliveryDate: "2025-02-21",
  },
  {
    orderId: "ORD013",
    customer: "Larry Scott",
    orderStatus: "Shipped",
    totalAmount: 180.75,
    discount: 12,
    deliveryDate: "2025-02-19",
  },
  {
    orderId: "ORD014",
    customer: "Mona Evans",
    orderStatus: "Pending",
    totalAmount: 95.0,
    discount: 0,
    deliveryDate: "2025-02-26",
  },
  {
    orderId: "ORD015",
    customer: "Nina Young",
    orderStatus: "Cancelled",
    totalAmount: 250.5,
    discount: 8,
    deliveryDate: "2025-02-13",
  },
  {
    orderId: "ORD016",
    customer: "Oscar Green",
    orderStatus: "Delivered",
    totalAmount: 40.0,
    discount: 0,
    deliveryDate: "2025-02-28",
  },
  {
    orderId: "ORD017",
    customer: "Paul Hall",
    orderStatus: "Shipped",
    totalAmount: 110.0,
    discount: 10,
    deliveryDate: "2025-02-17",
  },
  {
    orderId: "ORD018",
    customer: "Quinn Adams",
    orderStatus: "Pending",
    totalAmount: 70.25,
    discount: 0,
    deliveryDate: "2025-02-23",
  },
  {
    orderId: "ORD019",
    customer: "Rachel Martin",
    orderStatus: "Cancelled",
    totalAmount: 220.0,
    discount: 15,
    deliveryDate: "2025-02-11",
  },
  {
    orderId: "ORD020",
    customer: "Sam Carter",
    orderStatus: "Delivered",
    totalAmount: 55.0,
    discount: 0,
    deliveryDate: "2025-02-29",
  },
  {
    orderId: "ORD021",
    customer: "Tina Bell",
    orderStatus: "Shipped",
    totalAmount: 130.75,
    discount: 7,
    deliveryDate: "2025-02-15",
  },
  {
    orderId: "ORD022",
    customer: "Uma Reed",
    orderStatus: "Pending",
    totalAmount: 80.5,
    discount: 0,
    deliveryDate: "2025-02-25",
  },
  {
    orderId: "ORD023",
    customer: "Vera Cox",
    orderStatus: "Cancelled",
    totalAmount: 200.0,
    discount: 10,
    deliveryDate: "2025-02-10",
  },
  {
    orderId: "ORD024",
    customer: "Will Knight",
    orderStatus: "Delivered",
    totalAmount: 45.0,
    discount: 0,
    deliveryDate: "2025-02-20",
  },
  {
    orderId: "ORD025",
    customer: "Xena Lee",
    orderStatus: "Shipped",
    totalAmount: 120.0,
    discount: 15,
    deliveryDate: "2025-02-18",
  },
  {
    orderId: "ORD026",
    customer: "Yara Scott",
    orderStatus: "Pending",
    totalAmount: 75.25,
    discount: 0,
    deliveryDate: "2025-02-22",
  },
  {
    orderId: "ORD027",
    customer: "Zane Collins",
    orderStatus: "Cancelled",
    totalAmount: 300.0,
    discount: 20,
    deliveryDate: "2025-02-12",
  },
  {
    orderId: "ORD028",
    customer: "Abby Wilson",
    orderStatus: "Delivered",
    totalAmount: 50.0,
    discount: 0,
    deliveryDate: "2025-02-24",
  },
  {
    orderId: "ORD029",
    customer: "Blake Harris",
    orderStatus: "Shipped",
    totalAmount: 99.99,
    discount: 5,
    deliveryDate: "2025-02-16",
  },
  {
    orderId: "ORD030",
    customer: "Cathy Clark",
    orderStatus: "Pending",
    totalAmount: 85.5,
    discount: 0,
    deliveryDate: "2025-02-27",
  },
  {
    orderId: "ORD031",
    customer: "Dylan King",
    orderStatus: "Cancelled",
    totalAmount: 150.0,
    discount: 10,
    deliveryDate: "2025-02-14",
  },
  {
    orderId: "ORD032",
    customer: "Eli Turner",
    orderStatus: "Delivered",
    totalAmount: 65.0,
    discount: 0,
    deliveryDate: "2025-02-21",
  },
  {
    orderId: "ORD033",
    customer: "Faith Lewis",
    orderStatus: "Shipped",
    totalAmount: 180.75,
    discount: 12,
    deliveryDate: "2025-02-19",
  },
  {
    orderId: "ORD034",
    customer: "Gina Evans",
    orderStatus: "Pending",
    totalAmount: 95.0,
    discount: 0,
    deliveryDate: "2025-02-26",
  },
  {
    orderId: "ORD035",
    customer: "Hank Young",
    orderStatus: "Cancelled",
    totalAmount: 250.5,
    discount: 8,
    deliveryDate: "2025-02-13",
  },
  {
    orderId: "ORD036",
    customer: "Iris Green",
    orderStatus: "Delivered",
    totalAmount: 40.0,
    discount: 0,
    deliveryDate: "2025-02-28",
  },
  {
    orderId: "ORD037",
    customer: "Jake Hall",
    orderStatus: "Shipped",
    totalAmount: 110.0,
    discount: 10,
    deliveryDate: "2025-02-17",
  },
  {
    orderId: "ORD038",
    customer: "Kara Adams",
    orderStatus: "Pending",
    totalAmount: 70.25,
    discount: 0,
    deliveryDate: "2025-02-23",
  },
  {
    orderId: "ORD039",
    customer: "Leo Martin",
    orderStatus: "Cancelled",
    totalAmount: 220.0,
    discount: 15,
    deliveryDate: "2025-02-11",
  },
  {
    orderId: "ORD040",
    customer: "Mia Carter",
    orderStatus: "Delivered",
    totalAmount: 55.0,
    discount: 0,
    deliveryDate: "2025-02-29",
  },
  {
    orderId: "ORD041",
    customer: "Nolan Bell",
    orderStatus: "Shipped",
    totalAmount: 130.75,
    discount: 7,
    deliveryDate: "2025-02-15",
  },
  {
    orderId: "ORD042",
    customer: "Olivia Reed",
    orderStatus: "Pending",
    totalAmount: 80.5,
    discount: 0,
    deliveryDate: "2025-02-25",
  },
  {
    orderId: "ORD043",
    customer: "Peter Cox",
    orderStatus: "Cancelled",
    totalAmount: 200.0,
    discount: 10,
    deliveryDate: "2025-02-10",
  },
  {
    orderId: "ORD044",
    customer: "Quincy Knight",
    orderStatus: "Delivered",
    totalAmount: 45.0,
    discount: 0,
    deliveryDate: "2025-02-20",
  },
  {
    orderId: "ORD045",
    customer: "Rita Lee",
    orderStatus: "Shipped",
    totalAmount: 120.0,
    discount: 15,
    deliveryDate: "2025-02-18",
  },
  {
    orderId: "ORD046",
    customer: "Steve Scott",
    orderStatus: "Pending",
    totalAmount: 75.25,
    discount: 0,
    deliveryDate: "2025-02-22",
  },
  {
    orderId: "ORD047",
    customer: "Tara Collins",
    orderStatus: "Cancelled",
    totalAmount: 300.0,
    discount: 20,
    deliveryDate: "2025-02-12",
  },
  {
    orderId: "ORD048",
    customer: "Uma Wilson",
    orderStatus: "Delivered",
    totalAmount: 50.0,
    discount: 0,
    deliveryDate: "2025-02-24",
  },
  {
    orderId: "ORD049",
    customer: "Vince Harris",
    orderStatus: "Shipped",
    totalAmount: 99.99,
    discount: 5,
    deliveryDate: "2025-02-16",
  },
  {
    orderId: "ORD050",
    customer: "Wendy Clark",
    orderStatus: "Pending",
    totalAmount: 85.5,
    discount: 0,
    deliveryDate: "2025-02-27",
  },
];
